### ISSUE TITLE
Error While running the code

### ISSUE THREAD

**Issue by mohsen-alihosseini** [lxf8519/DL-hybrid-precoder#4]
Traceback (most recent call last):
  File "main_train_beamforming.py", line 47, in <module>
    precoder=ConvPrecoder(data_dim,[N_BS,N_MS,M_BS,M_MS],num_classes)
  File "D:\Python\Projects\ML\DL-hybrid-precoder\Model\conv1D_precoder.py", line 30, in __init__
    kernel_initializer='complex_independent',name='Conv_P'))(encoded)
  File "D:\Python\Projects\ML\venv\lib\site-packages\keras\engine\base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "D:\Python\Projects\ML\DL-hybrid-precoder\Complex_layers\conv.py", line 212, in build
    constraint=self.kernel_constraint
TypeError: add_weight() got multiple values for argument 'name'

![19c05085-ef53-4213-a552-a70a740b4b6a](https://user-images.githubusercontent.com/42588631/88910156-4476df80-d271-11ea-8808-71e9957f5869.jpg)

**Comment by lxf8519** [comment]
> Traceback (most recent call last):
> File "main_train_beamforming.py", line 47, in
> precoder=ConvPrecoder(data_dim,[N_BS,N_MS,M_BS,M_MS],num_classes)
> File "D:\Python\Projects\ML\DL-hybrid-precoder\Model\conv1D_precoder.py", line 30, in **init**
> kernel_initializer='complex_independent',name='Conv_P'))(encoded)
> File "D:\Python\Projects\ML\venv\lib\site-packages\keras\engine\base_layer.py", line 463, in **call**
> self.build(unpack_singleton(input_shapes))
> File "D:\Python\Projects\ML\DL-hybrid-precoder\Complex_layers\conv.py", line 212, in build
> constraint=self.kernel_constraint
> TypeError: add_weight() got multiple values for argument 'name'
> 
> ![19c05085-ef53-4213-a552-a70a740b4b6a](https://user-images.githubusercontent.com/42588631/88910156-4476df80-d271-11ea-8808-71e9957f5869.jpg)

This issue may come from tensorflow 2.0. The code is written and tested in TF 1.13.1 which is mentioned in the instruction page. Note that TF 2.0 is not directly compatible with TF 1.xx. Please have a try to use the same environment. Thanks.

**Comment by mohsen-alihosseini** [comment]
thanks for your reply
I had used the same version that mentioned in instruction page
My environment is:
Python      3.7.4
tensorflow           1.13.1
Can I have more help ?

**Comment by lxf8519** [comment]
Please try TF 1.12.0 and Keras 2.2.4.
